{
 "title": "TEST_DASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "country", "label": "Country", "query": "AU,IN,US" },
   {
    "name": "query_country",
    "label": "Country_Q",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"}, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "PaymentMethod",
    "query": {
     "query": "label_values(shoehub_payments, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "비즈니스 차트", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$paymentMethod 사용량 분석",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "shoehub_payments{PaymentMethod=\"Card\"}",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "Card Payments in Countries",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "{{CountryCode}}"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "$country 5퍼센트 이하 확인용",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"} ) / sum(shoehub_payments{CountryCode=\"$country\"} ) * 100",
     "legendFormat": "PayPal"
    }
   ]
  },
  {
   "title": "현재 vs 1분 전",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval])",
     "legendFormat": "현재"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval] offset 1m)",
     "legendFormat": "1분전"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=~\"HighHeels|Boots|Loafers\"}[5m])",
     "legendFormat": "{{ShoeType}}"
    },
    {
     "expr": "sum(rate(shoehub_sales{ShoeType=~\"Boots|HighHeels\"}[5m])) by (instance, job)",
     "legendFormat": "SUM(Boot, HighHeels)"
    }
   ]
  },
  {
   "title": "게이지를 total Type 으로 변환해서 사용",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "시스템 차트", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "응답 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}