version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/yaml/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/yaml/web.yml:/etc/prometheus/web.yml
      - ./prometheus/yaml/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./local_home/prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  # https://github.com/Einsteinish/Docker-Compose-Prometheus-and-Grafana
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    volumes:
      - ./local_home/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 9000:3000
    depends_on:
      - prometheus

  # https://github.com/aussiearef/ShoeHubV2
  shoehub-exporter:
    image: aussiearef/shoehub
    container_name: test-server
    ports:
      - 8000:8080
