apiVersion: 1
groups:
    - orgId: 1
      name: Card Payments
      folder: MyFolder
      interval: 1m
      rules:
        - uid: fe1g6da2dgh6oe
          title: Payment Card
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: "1111"
              model:
                datasource:
                    type: prometheus
                    uid: "1111"
                editorMode: code
                expr: shoehub_payments{PaymentMethod="Card"}
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: '{{CountryCode}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 600
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ee1b1kz4kzcw0f
          panelId: 9
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ee1b1kz4kzcw0f
            __panelId__: "9"
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
    - orgId: 1
      name: dooly-world
      folder: Dooly.World
      interval: 1m
      rules:
        - uid: cefp0rxy64nwga
          title: CPU_usage_percent_warning
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: "1111"
              model:
                disableTextWrap: false
                editorMode: code
                expr: (((count(count(node_cpu_seconds_total{instance="192.168.234.207:9100",job=~"node-exporter"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance="192.168.234.207:9100",job=~"node-exporter"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance="192.168.234.207:9100",job=~"node-exporter"}) by (cpu))
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 30
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: ontact_slack
