---

- name: Install custom themes
  git:
    repo: "{{ theme.repo }}"
    dest: "/root/.oh-my-zsh/custom/themes/{{ theme.name }}"
    version: "{{ theme.version | default(omit) }}"
    update: "{{ theme.update | default(omit) | bool }}"
  with_items: "{{ ohmyzsh_default_custom_themes }}"
  when: ohmyzsh_default_custom_themes is defined
  loop_control:
    loop_var: theme

- name: Set permissions for themes
  become: yes
  file:
    path: '/root/.oh-my-zsh/custom/themes/{{ theme.name }}'
    owner: "root"
    group: "root"
    mode: '0750'
  with_items: "{{ ohmyzsh_default_custom_themes }}"
  when: ohmyzsh_default_custom_themes is defined
  loop_control:
    loop_var: theme

- name: Link custom themes to ohmyzsh directory
  file:
    src: "/root/.oh-my-zsh/custom/themes/{{ theme.name }}/{{ theme.name }}.zsh-theme"
    dest: "/root/.oh-my-zsh/themes/{{ theme.name }}.zsh-theme"
    owner: "root"
    group: "root"
    state: link
  with_items: "{{ ohmyzsh_default_custom_themes }}"
  when: ohmyzsh_default_custom_themes is defined
  loop_control:
    loop_var: theme

- name: Write .p10k.zsh file from template
  become: yes
  copy:
    src: 'p10k.zsh'
    dest: '/root/.p10k.zsh'
    backup: yes
    owner: "root"
    group: "root"
    mode: '0640'
  when: ohmyzsh_default_custom_themes is defined
...
