---

- name: Install custom plugins
  git:
    repo: "{{ plugin.repo }}"
    dest: "/root/.oh-my-zsh/custom/plugins/{{ plugin.name }}"
    version: "{{ plugin.version | default(omit) }}"
    update: "{{ plugin.update | default(omit) | bool }}"
  when: ohmyzsh_default_custom_plugins is defined
  with_items: "{{ ohmyzsh_default_custom_plugins }}"
  loop_control:
    loop_var: plugin

- name: Set permissions for plugins
  become: yes
  file:
    path: '/root/.oh-my-zsh/custom/plugins/{{ plugin.name }}'
    owner: "root"
    group: "root"
    mode: '0750'
  with_items: "{{ ohmyzsh_default_custom_plugins }}"
  when: ohmyzsh_default_custom_plugins is defined
  loop_control:
    loop_var: plugin

...
