apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
    rule_files:
      - /etc/prometheus/alert.rules.yml

  alert.rules.yml: |
    groups:
      - name: example
        rules:
          - alert: HighMemoryUsage
            expr: node_memory_Active_bytes / node_memory_MemTotal_bytes * 100 > 3
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High Memory Usage"
              description: "Memory usage is above 3% for more than 5 minutes."
